### ISSUE TITLE
Error encountered

### ISSUE THREAD

**Issue by gaurangfgupta** [sindresorhus/trash-cli#12]
`>trash build`
Error: Command failed: (project_path)\node_modules\trash\lib\win-trash.exe (project_path)\build

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\
\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! (project_name)@0.0.1 build: `trash build`
npm ERR! Exit status 1
...
...

**Comment by SamVerschueren** [comment]
Is a file in that directory currently being executed?

**Comment by gaurangfgupta** [comment]
No. The same runs fine on Mac but not on Windows.

**Comment by ganesh47** [comment]
is there a workaround for this in windows?

**Comment by sindresorhus** [comment]
Doesn't look like a problem with this package.
