### ISSUE TITLE
Error from Update Notifier module

### ISSUE THREAD

**Issue by kknopper** [sindresorhus/trash-cli#27]
I recently updated my version of trash-cli, and I have been getting the following error:

```
/usr/local/lib/node_modules/trash-cli/node_modules/update-notifier/index.js:74
                        (async () => {
                               ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/trash-cli/cli.js:3:24)
```

I'm on npm version 6.9.0 - not sure if anyone else is seeing this.
Not sure if this an issue I should open with the update-notifier module or not

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/trash-cli/releases/tag/v2.0.0

> Require Node.js 8 2bb419f
