### ISSUE TITLE
Can't trash folders with content

### ISSUE THREAD

**Issue by SonOfDiablo** [sindresorhus/trash-cli#30]
When trying to trash a folder with any content (be it other folders or files) an error is thrown:
```
at ChildProcess.exithandler (child_process.js:303:12)
at ChildProcess.emit (events.js:321:20)
at maybeClose (internal/child_process.js:1026:16)
at Socket.<anonymous> (internal/child_process.js:441:11)
at Socket.emit (events.js:321:20)
at Pipe.<anonymous> (net.js:672:12)
```

I have checked and no process is currently using the folder or any files/folders within it.

I'm also able to trash files just fine, as well as folders that do not have any content.

My system:
OS: Windows 10 Home Version 1909 Build 18363
NodeJS: v13.9.0
trash-cli: 3.0.0
trash: 6.1.1
Env: PowerShell 6.2.4

**Comment by SonOfDiablo** [comment]
My bad, something *was* using some of the files, I just didn't see it initially...
