### ISSUE TITLE
v5 throws ERR_UNSUPPORTED_ESM_URL_SCHEME error

### ISSUE THREAD

**Issue by jonbcampos-alto** [sindresorhus/trash-cli#35]
Notes from my build:

Step #3: > trash build
Step #3: 
Step #3: internal/modules/run_main.js:54
Step #3:     internalBinding('errors').triggerUncaughtException(
Step #3:                               ^
Step #3: 
Step #3: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
Step #3:     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:669:11)
Step #3:     at Loader.resolve (internal/modules/esm/loader.js:97:40)
Step #3:     at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
Step #3:     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
Step #3:     at link (internal/modules/esm/module_job.js:41:36) {
Step #3:   code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
Step #3: }
Step #3: npm ERR! code ELIFECYCLE
Step #3: npm ERR! errno 1
Step #3: npm ERR! <my project>@0.0.1 clean: `trash build`
Step #3: npm ERR! Exit status 1
Step #3: npm ERR!

**Comment by sindresorhus** [comment]
Don't think this is relevant anymore.
